// Code generated by sprotodump
// source: echo.sproto
// DO NOT EDIT!

/*
   Package sproto_echo is a generated sproto package.
*/
package sproto_echo

import (
	"reflect"

	"github.com/xjdrew/gosproto"
)

type PingResponse struct {
	Pong *string `sproto:"string,0,name=pong"`
}

type PingRequest struct {
	Ping *string `sproto:"string,0,name=ping"`
}

var Name string = "echo"
var Protocols []*sproto.Protocol = []*sproto.Protocol{
	&sproto.Protocol{
		Type:       1,
		Name:       "echo.ping",
		MethodName: "Echo.Ping",
		Request:    reflect.TypeOf(&PingRequest{}),
		Response:   reflect.TypeOf(&PingResponse{}),
	},
}
